import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'; 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const myFont = localFont({
  src: [
    {
      path: '../../public/fonts/Pixel Digivolve.otf',
      weight: '400',  // Adjust based on font variations
      style: 'normal',
    }
  ],
  display: 'swap',
  variable: '--font-myfont'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth"  >
      <body
        className={`${myFont.className} ${geistMono.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
